import type { ProjectAnalysis } from "../types/index.js";

export function generateAutoArchitecture(projectName: string, analysis: ProjectAnalysis): string {
  const sections: string[] = [];
  sections.push(`# ${projectName} — Architecture Overview`);
  sections.push("");
  sections.push("> Auto-generated by OpenHarness. Review and adjust as needed.");
  sections.push("");
  sections.push("## Architecture Style");
  sections.push("");
  sections.push(`${analysis.mode} architecture`);
  sections.push("");
  sections.push("## Detected Technologies");
  sections.push("");
  sections.push(`- **Languages**: ${analysis.languages.join(", ") || "Unknown"}`);
  sections.push(`- **Frameworks**: ${analysis.frameworks.join(", ") || "Unknown"}`);
  sections.push(`- **Build Tools**: ${analysis.buildTools.join(", ") || "Unknown"}`);
  sections.push(`- **Package Manager**: ${analysis.packageManager}`);
  sections.push("");

  if (analysis.services.length > 1) {
    sections.push("## Services");
    sections.push("");
    sections.push("| Service | Language | Framework |");
    sections.push("|---------|----------|-----------|");
    for (const svc of analysis.services) {
      sections.push(`| ${svc.name} | ${svc.language ?? "-"} | ${svc.framework ?? "-"} |`);
    }
    sections.push("");
  }

  sections.push("## Key Technical Decisions");
  sections.push("");
  sections.push("| Decision | Choice | Reason |");
  sections.push("|----------|--------|--------|");
  sections.push("| _(to be filled)_ | — | — |");
  sections.push("");
  sections.push("---");
  sections.push("");
  sections.push("*Maintained by the architect. Major changes require review.*");
  return sections.join("\n");
}

export function generateArchitectureTemplate(projectName: string): string {
  return `# ${projectName} — Architecture Overview

> This file describes your project's architecture. AI assistants read this first.

---

## Architecture Style

_(Describe your project's architecture: monolith, microservices, etc.)_

## Modules

| Module | Description | Key Files |
|--------|------------|-----------|
| _(to be filled)_ | — | — |

## Key Technical Decisions

| Decision | Choice | Reason |
|----------|--------|--------|
| _(to be filled)_ | — | — |

---

*Maintained by the architect. Major changes require review.*
`;
}

export function generateImplicitContractsTemplate(): string {
  return `# Implicit Contracts / Project Pitfalls

> **Core Principle**: Every project has "everyone knows but nobody writes down" conventions.
> These implicit contracts are high-risk zones for bugs and rework. **Must be made explicit.**

---

## How to Use This File

1. **Propose Phase**: Check against this file in design.md
2. **Apply Phase**: Follow conventions when implementing code
3. **Review Phase**: Reviewer agent checks against this file
4. **When you hit a pitfall**: Add it immediately (whoever hits it, adds it)

---

## Contract List

### 🔴 Critical (Violation causes production incidents)

| # | Convention | Surface Rule | Actual Requirement | Incident Log |
|---|-----------|-------------|-------------------|--------------|
| 1 | _(to be filled)_ | — | — | — |

### 🟡 Important (Violation causes rework)

| # | Convention | Surface Rule | Actual Requirement | Incident Log |
|---|-----------|-------------|-------------------|--------------|
| 1 | _(to be filled)_ | — | — | — |

### 🟢 Suggested (Team conventions)

| # | Convention | Surface Rule | Actual Requirement | Incident Log |
|---|-----------|-------------|-------------------|--------------|
| 1 | _(to be filled)_ | — | — | — |

---

## Change Log

| Date | Added By | Contract | Reason |
|------|----------|----------|--------|
| _(auto)_ | — | — | — |

---

*This file is the single source of truth for project pitfalls. Update immediately when discovering new ones.*
`;
}

export function generateOpenSpecConfig(): string {
  return `# OpenSpec Configuration — managed by OpenHarness

profile: default
delivery: incremental

proposal:
  requireImpactSection: true
  requireApiContractReference: false
  requireChangeType: true
  draftByDefault: true

specs:
  requireScenarioPerRequirement: true
  scenarioFormat: given-when-then
  mappableToAcceptanceCriteria: true
  normativeLanguage: true

design:
  referenceDevMap: true
  checkImplicitContracts: true
  requireMigrationPlan: false
  requireApiVersioning: false

tasks:
  requireStack: true
  requireService: false
  requireExplicitDependencies: true
  granularity: medium
  requireCrossServiceImpact: false

verify:
  scope: changed
  excludeCodeReview: false
  excludeArchitectureReview: false
  checkImplicitContracts: true

archive:
  syncSpecs: true
  updateBoardJson: true
  updateDevMap: true
`;
}
